### ISSUE TITLE
ERROR: first argument must be a vector

### ISSUE THREAD

**Issue by asaki1986** [sztup/scarHRD#12]
Hi,

After loading the scarHRD package, I run the command 
`scar_score("small.seqz.gz",reference = "grch37", seqz=TRUE)`
but returns 
`Error in split.default(lis_obj, names(lis_obj)) :
  first argument must be a vector`

seqz file:
> head(a)
  chromosome position base.ref depth.normal depth.tumor depth.ratio    Af Bf
1          1   131036        N            2          27      19.167 1.000  0
2          1   131087        N            2          42      21.743 1.000  0
3          1   131138        N            3          64      22.624 1.000  0
4          1   131174        A            2          57      28.500 0.982  0
5          1   131189        N            2          66      36.526 1.000  0
6          1   131240        N            2          51      32.949 1.000  0
  zygosity.normal GC.percent good.reads AB.normal AB.tumor tumor.strand
1             hom         70         51         N        .            0
2             hom         73         50         N        .            0
3             hom         62         51         N        .            0
4             hom         62         57         A   C0.018         C1.0
5             hom         63         51         N        .            0
6             hom         58         49         N        .            0
>

The difference between the input file I provided and the test file in repo is the 'chr' label in chrom col.

Any suggestions?

Thanks

**Comment by vymao** [comment]
Hi, did you ever resolve this? I am trying to run this package with a b37 reference and am getting the same error.

**Comment by sternp** [comment]
I'm also having the same issue using grch37. 

Using chr.in.names = FALSE did not help.

Any luck with this?

**Comment by sternp** [comment]
Okay, you have to manually add chr to each chromosome number. The chr.in.names option doesn't seem to work.

**Comment by sztup** [comment]
Hi, thanks for reporting it, it is solved now.
